import { createUseStyles } from "react-jss";

export default createUseStyles({
  container: {
    display: "grid",
    // gridTemplateColumns: '100px 100px 100px 100px 100px 100px',
    gridTemplateColumns: "100px ".repeat(sessionStorage.getItem("cuadricula")),
    gridGap: "0",
  },
  trianglebottomleft: {
    width: "0",
    height: "0",
    borderRight: "50px solid #000000",
    borderTop: "75px solid #000000",
    borderLeft: "50px solid transparent",
    borderBottom: "75px solid transparent",
    position: "relative",
    cursor: "pointer",
    transition: "all 200ms linear",
    "&:hover": {
      transform: "scale(1.1)",
    },
    "&:after": {
      content: '""',
      width: "0",
      height: "0",
      borderRight: "47px solid #a7c8eb",
      borderTop: "72px solid #a7c8eb",
      borderLeft: "47px solid transparent",
      borderBottom: "70px solid transparent",
      position: "absolute",
      top: "-74px",
      left: "-46px",
    },
  },
  trianglebottomright: {
    width: "0",
    height: "0",
    borderRight: "50px solid transparent",
    borderTop: "75px solid #000000",
    borderLeft: "50px solid #000000",
    borderBottom: "75px solid transparent",
    position: "relative",
    cursor: "pointer",
    transition: "all 200ms linear",
    "&:hover": {
      transform: "scale(1.1)",
    },
    "&:after": {
      content: '""',
      width: "0",
      height: "0",
      borderRight: "47px solid transparent",
      borderTop: "72px solid #f0ad4e",
      borderLeft: "47px solid #f0ad4e",
      borderBottom: "70px solid transparent",
      position: "absolute",
      top: "-74px",
      left: "-48px",
    },
  },
  triangletopleft: {
    width: "0",
    height: "0",
    borderRight: "50px solid #000000",
    borderTop: "75px solid transparent",
    borderLeft: "50px solid transparent",
    borderBottom: "75px solid #000000",
    position: "relative",
    cursor: "pointer",
    transition: "all 200ms linear",
    "&:hover": {
      transform: "scale(1.1)",
    },
    "&:after": {
      content: '""',
      width: "0",
      height: "0",
      borderRight: "47px solid #a7c8eb",
      borderTop: "72px solid transparent",
      borderLeft: "47px solid transparent",
      borderBottom: "70px solid #a7c8eb",
      position: "absolute",
      top: "-69px",
      left: "-46px",
    },
  },
  triangletopright: {
    width: "0",
    height: "0",
    borderRight: "50px solid transparent",
    borderTop: "75px solid transparent",
    borderLeft: "50px solid #000000",
    borderBottom: "75px solid #000000",
    position: "relative",
    cursor: "pointer",
    transition: "all 200ms linear",
    "&:hover": {
      transform: "scale(1.1)",
    },
    "&:after": {
      content: '""',
      width: "0",
      height: "0",
      borderRight: "47px solid transparent",
      borderTop: "72px solid transparent",
      borderLeft: "47px solid #a7c8eb",
      borderBottom: "70px solid #a7c8eb",
      position: "absolute",
      top: "-69px",
      left: "-48px",
    },
  },
  rectangle1: {
    height: "150px",
    width: "100px",
    background: "#18cc08",
    border: "2px solid black",
  },
  rectangle2: {
    height: "150px",
    width: "100px",
    background: "ffffff",
    border: "2px solid black",
  },
});
